services:
  symfony_app:
    build: .
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8080:80"
    depends_on:
      - symfony_mysql
      - symfony_redis

  symfony_mysql:
    image: mysql:8
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: creditcompare
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  symfony_redis:
    image: redis:latest
    container_name: symfony_redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: symfony_mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"
    depends_on:
      - symfony_mysql

  symfony_scheduler:
    build: .  # uses the same Dockerfile as symfony_app
    container_name: symfony_scheduler
    working_dir: /var/www/html
    command: sh -c "until mysqladmin ping -h symfony_mysql --silent; do sleep 5; done && php bin/console messenger:consume scheduler_creditcard_import --time-limit=60 --limit=1; sleep 60;"
    depends_on:
      symfony_app:
        condition: service_started
      symfony_mysql:
        condition: service_healthy
      symfony_redis:
        condition: service_started

volumes:
  mysql_data:
